name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install fish
        run: brew install fish
      - name: Remove fish
        run: brew remove fish
      - name: Install ncurses
        run: brew install ncurses
      - name: Autoremove formulae
        run: brew autoremove --force
      - name: Test formulae
        run: test "$(brew list)" = "ncurses"
